// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// timesTwo
NumericVector timesTwo(NumericVector x);
RcppExport SEXP bob_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}
// ceps
double ceps(double rate, double win_length_ms, double win_shift_ms, double n_filters, double n_ceps, double f_min, double f_max, double delta_win, double pre_emphasis_coeff, bool mel_scale, bool dct_norm);
RcppExport SEXP bob_ceps(SEXP rateSEXP, SEXP win_length_msSEXP, SEXP win_shift_msSEXP, SEXP n_filtersSEXP, SEXP n_cepsSEXP, SEXP f_minSEXP, SEXP f_maxSEXP, SEXP delta_winSEXP, SEXP pre_emphasis_coeffSEXP, SEXP mel_scaleSEXP, SEXP dct_normSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type win_length_ms(win_length_msSEXP);
    Rcpp::traits::input_parameter< double >::type win_shift_ms(win_shift_msSEXP);
    Rcpp::traits::input_parameter< double >::type n_filters(n_filtersSEXP);
    Rcpp::traits::input_parameter< double >::type n_ceps(n_cepsSEXP);
    Rcpp::traits::input_parameter< double >::type f_min(f_minSEXP);
    Rcpp::traits::input_parameter< double >::type f_max(f_maxSEXP);
    Rcpp::traits::input_parameter< double >::type delta_win(delta_winSEXP);
    Rcpp::traits::input_parameter< double >::type pre_emphasis_coeff(pre_emphasis_coeffSEXP);
    Rcpp::traits::input_parameter< bool >::type mel_scale(mel_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type dct_norm(dct_normSEXP);
    rcpp_result_gen = Rcpp::wrap(ceps(rate, win_length_ms, win_shift_ms, n_filters, n_ceps, f_min, f_max, delta_win, pre_emphasis_coeff, mel_scale, dct_norm));
    return rcpp_result_gen;
END_RCPP
}
