# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('bob_timesTwo', PACKAGE = 'bob', x)
}

ceps <- function(rate, win_length_ms = 20, win_shift_ms = 10, n_filters = 24, n_ceps = 19, f_min = 0., f_max = 4000., delta_win = 2, pre_emphasis_coeff = 1.0, mel_scale = TRUE, dct_norm = TRUE) {
    .Call('bob_ceps', PACKAGE = 'bob', rate, win_length_ms, win_shift_ms, n_filters, n_ceps, f_min, f_max, delta_win, pre_emphasis_coeff, mel_scale, dct_norm)
}

